# Generated by Django 4.2.3 on 2023-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('class_and_section', models.TextField()),
                ('recommendations', models.TextField()),
            ],
        ),
    ]
